// src/components/ProjectCard.tsx
import { Link } from 'react-router-dom';

type ProjectProps = {
  slug: string;
  title: string;
  description: string;
  tech: string[];
};

export default function ProjectCard({ slug, title, description, tech }: ProjectProps) {
  return (
    <Link 
      to={`/projects/${slug}`}
      className="block h-full group"
    >
      <div className="rounded-xl border border-neutral-200 bg-white p-6 shadow-sm hover:shadow-md transition-all h-full flex flex-col">
        <h3 className="text-lg font-semibold text-neutral-900 mb-2 group-hover:text-green-600 transition-colors">
          {title}
        </h3>
        <p className="text-sm text-neutral-600 mb-4 leading-relaxed flex-grow">
          {description}
        </p>
        
        <div className="flex flex-wrap gap-2 mt-auto">
           {tech.slice(0, 3).map(t => (
             <span key={t} className="text-xs text-neutral-400 bg-neutral-50 px-2 py-1 rounded">
               {t}
             </span>
           ))}
        </div>
      </div>
    </Link>
  );
}

// src/components/ProjectCard.vue
<script setup lang="ts">
import type { Project } from "@/types";

defineProps<Pick<Project, "slug" | "title" | "description" | "tags" | "date">>();
</script>

<template>
  <RouterLink
    :to="`/projects/${slug}`"
    class="flex flex-col gap-2 p-5 rounded-lg border border-line bg-white hover:border-moss transition group"
  >
    <div class="flex items-center justify-between">
      <p class="text-ink font-medium group-hover:text-moss transition">{{ title }}</p>
      <p class="text-sm text-muted">{{ date.slice(0, 4) }}</p>
    </div>
    <p class="text-muted text-sm">{{ description }}</p>
    <div class="flex items-end justify-between mt-1">
      <div class="flex flex-wrap gap-2">
        <span
          v-for="tag in tags"
          :key="tag"
          class="text-xs text-pine bg-moss-soft px-3 py-0.5 rounded-full"
        >{{ tag }}</span>
      </div>
      <span class="text-muted group-hover:text-moss transition">&rarr;</span>
    </div>
  </RouterLink>
</template>
