// src/App.tsx
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import Header from './components/Header';
import Footer from './components/Footer';
import Home from './pages/Home';
import Projects from './pages/Projects';

export default function App() {
  return (
    <BrowserRouter>
      <div className="flex flex-col min-h-screen">
        <Header />
        <main className="flex-grow flex">
          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="/projects" element={<Projects />} />
            <Route path="*" element={<Navigate to="/" replace />} />
          </Routes>
        </main>
        <Footer />
      </div>
    </BrowserRouter>
  );
}

// src/App.vue
<script setup lang="ts">
import { RouterView } from "vue-router";
import Header from "@/components/Header.vue"
import Footer from "@/components/Footer.vue"
</script>

<template>
  <main class="flex flex-col min-h-screen bg-paper">
    <Header class="fixed top-0 left-0 right-0 z-10 bg-paper border-b border-line"/>
    <RouterView class="flex-1 pt-16" />
    <Footer />
  </main>
</template>
